services:
  postgres:
    image: postgres:13.3
    container_name: rk3
    environment:
      POSTGRES_DB: "rk3_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - /home/dmitriy/bmstu/DB/rk3:/mnt
    ports:
      - "5432:5432"
